### ISSUE TITLE
Hesap bilgileri kalmış

### ISSUE THREAD

**Issue by eyupfidan** [bilallgunaydin/A101-Test-Otomasyon-Practicum-Final-Case#1]
https://github.com/bilallgunaydin/A101-Test-Otomasyon-Practicum-Final-Case/blob/main/src/test/java/PageObjectModel/LoginPage.java 

ilgili linkte hesap bilgileri kalmış

**Comment by bilallgunaydin** [comment]
Sorun yok. Test için açtığım bir hesaptı. Geri bildiriminz için teşekkür
ederim. İyi günler dilerim

Eyüp Fidan ***@***.***>, 9 Ara 2022 Cum, 17:12 tarihinde şunu
yazdı:
